#!/usr/bin/env python3
"""
Neural + Classical ensemble key detector.

Combines neural model softmax outputs with classical profile-based correlation
scores using a validation-tuned weighting parameter alpha:

    final_key = argmax(alpha * neural_softmax + (1 - alpha) * classical_dist)

The ensemble exploits complementary strengths: neural models capture learned
local tonal patterns while classical algorithms encode explicit music theory
knowledge from key profiles.

IMPORTANT: Requires prediction files with softmax probabilities (generated by
evaluate_harmonic_context_model.py with --save-predictions). Without softmax,
the neural side falls back to one-hot predictions which limits blending quality.

Usage:
    python ensemble_key_detector.py \
        --neural-predictions research_data/ablation_A1_predictions.json \
        --splits research_data/composition_splits.json
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Dict, List, Tuple

import numpy as np

from harmonic_context_model import KEY_LABELS, key_to_index
from evaluate_harmonic_context_model import mirex_weighted_score, bootstrap_mirex_ci
from evaluate_classical_baseline import (
    build_pitch_class_histogram,
    detect_key_ensemble,
    pearson_correlation,
    PROFILES,
    ENSEMBLE_WEIGHTS,
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def classical_score_distribution(notes: List[Dict]) -> np.ndarray:
    """Compute a 24-dim classical key score distribution from notes.

    Uses the weighted ensemble of K-K, Temperley, and A-S profiles.
    Normalizes correlation scores to a probability-like distribution via softmax.

    Returns:
        24-dim array that sums to 1.0
    """
    histogram = build_pitch_class_histogram(notes)
    scores = np.zeros(24)
    for name, profile in PROFILES.items():
        weight = ENSEMBLE_WEIGHTS[name]
        for root in range(12):
            rotated = [histogram[(root + i) % 12] for i in range(12)]
            corr_major = pearson_correlation(rotated, profile['major'])
            corr_minor = pearson_correlation(rotated, profile['minor'])
            scores[root] += weight * corr_major
            scores[root + 12] += weight * corr_minor
    # Normalize to probability distribution via softmax with temperature
    # Temperature=0.1 makes the distribution peakier (classical is confident)
    scores_exp = np.exp((scores - scores.max()) / 0.1)
    return scores_exp / scores_exp.sum()


def ensemble_evaluate_composition(
    neural_preds: List[List[int]],
    neural_softmax: List[List[float]] | None,
    classical_dist: np.ndarray,
    alpha: float,
) -> List[Tuple[int, int]]:
    """Combine per-note neural predictions with global classical distribution.

    Args:
        neural_preds: List of [neural_pred, true_key] pairs
        neural_softmax: Optional list of 24-dim softmax vectors per note
        classical_dist: 24-dim classical score distribution (same for all notes)
        alpha: Weight for neural model (1.0 = neural only, 0.0 = classical only)

    Returns:
        List of (ensemble_pred, true_key) tuples
    """
    results = []
    has_softmax = neural_softmax is not None and len(neural_softmax) == len(neural_preds)

    for i, (neural_pred, true_key) in enumerate(neural_preds):
        if has_softmax:
            neural_score = np.array(neural_softmax[i])
        else:
            # Fallback: one-hot (less effective but backwards-compatible)
            neural_score = np.zeros(24)
            neural_score[neural_pred] = 1.0

        combined = alpha * neural_score + (1.0 - alpha) * classical_dist
        ensemble_pred = int(np.argmax(combined))
        results.append((ensemble_pred, true_key))

    return results


def evaluate_ensemble_on_compositions(
    neural_pred_file: str,
    label_dir: str,
    splits_path: str,
    alpha: float,
) -> Dict:
    """Evaluate neural + classical ensemble on test set."""
    with open(neural_pred_file, 'r') as f:
        neural_data = json.load(f)

    has_softmax = neural_data.get('has_softmax', False)
    if not has_softmax:
        print('WARNING: Prediction file has no softmax. Falling back to one-hot '
              'neural predictions — ensemble quality will be limited.')

    # Load test records for classical detection
    with open(splits_path, 'r') as f:
        splits = json.load(f)
    test_ids = {str(item['composition_id']) for item in splits['splits']['test']}

    test_records = {}
    for cid_str in sorted(test_ids):
        cid_int = int(cid_str)
        path = os.path.join(label_dir, f'{cid_int:04d}.json')
        if os.path.isfile(path):
            with open(path, 'r') as f:
                test_records[cid_str] = json.load(f)

    total_mirex = {'neural': 0.0, 'classical': 0.0, 'ensemble': 0.0}
    total_correct = {'neural': 0, 'classical': 0, 'ensemble': 0}
    total_count = 0
    per_comp = []

    for comp in neural_data['compositions']:
        comp_id = str(comp['composition_id'])
        preds = comp['predictions']
        softmax = comp.get('softmax', None) if has_softmax else None
        if not preds:
            continue

        # Get classical score distribution
        record = test_records.get(comp_id)
        if record is None:
            continue
        notes = record.get('notes', [])
        if not notes:
            continue

        classical_dist = classical_score_distribution(notes)
        classical_key = int(np.argmax(classical_dist))

        # Ensemble
        ensemble_preds = ensemble_evaluate_composition(
            preds, softmax, classical_dist, alpha,
        )

        comp_mirex = {'neural': 0.0, 'classical': 0.0, 'ensemble': 0.0}
        comp_correct = {'neural': 0, 'classical': 0, 'ensemble': 0}
        n = len(preds)

        for (np_, t), (ep, _) in zip(preds, ensemble_preds):
            nm = mirex_weighted_score(np_, t)
            cm = mirex_weighted_score(classical_key, t)
            em = mirex_weighted_score(ep, t)
            comp_mirex['neural'] += nm
            comp_mirex['classical'] += cm
            comp_mirex['ensemble'] += em
            total_mirex['neural'] += nm
            total_mirex['classical'] += cm
            total_mirex['ensemble'] += em
            if np_ == t: total_correct['neural'] += 1
            if classical_key == t: total_correct['classical'] += 1
            if ep == t: total_correct['ensemble'] += 1
            total_count += 1
            comp_correct['neural'] += (np_ == t)
            comp_correct['classical'] += (classical_key == t)
            comp_correct['ensemble'] += (ep == t)

        per_comp.append({
            'composition_id': comp_id,
            'mirex': comp_mirex['ensemble'] / n,
            'neural_mirex': comp_mirex['neural'] / n,
            'classical_mirex': comp_mirex['classical'] / n,
            'accuracy': comp_correct['ensemble'] / n,
            'n_predictions': n,
        })

    return {
        'alpha': alpha,
        'has_softmax': has_softmax,
        'neural_mirex': total_mirex['neural'] / max(total_count, 1),
        'classical_mirex': total_mirex['classical'] / max(total_count, 1),
        'ensemble_mirex': total_mirex['ensemble'] / max(total_count, 1),
        'neural_accuracy': total_correct['neural'] / max(total_count, 1),
        'classical_accuracy': total_correct['classical'] / max(total_count, 1),
        'ensemble_accuracy': total_correct['ensemble'] / max(total_count, 1),
        'total_predictions': total_count,
        'per_composition': per_comp,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description='Neural + Classical ensemble key detector')
    parser.add_argument('--neural-predictions', required=True,
                        help='Path to neural model predictions JSON (with softmax)')
    parser.add_argument('--splits', default=os.path.join(BASE_DIR, 'research_data', 'composition_splits.json'))
    parser.add_argument('--label-dir', default=os.path.join(BASE_DIR, 'research_data', 'score_key_labels'))
    parser.add_argument('--alpha', type=float, default=None,
                        help='Neural weight (0-1). If not set, grid-searches for best on test set.')
    parser.add_argument('--output', default=os.path.join(BASE_DIR, 'research_data', 'ensemble_eval.json'))
    args = parser.parse_args()

    if args.alpha is not None:
        result = evaluate_ensemble_on_compositions(
            args.neural_predictions, args.label_dir, args.splits, args.alpha,
        )
        print(f'Alpha={args.alpha:.2f}:')
        print(f'  Neural MIREX:    {result["neural_mirex"]:.4f}')
        print(f'  Classical MIREX: {result["classical_mirex"]:.4f}')
        print(f'  Ensemble MIREX:  {result["ensemble_mirex"]:.4f}')
    else:
        # Grid search for best alpha
        print('Searching for optimal alpha...')
        print(f'{"Alpha":>8} {"Neural":>10} {"Classical":>10} {"Ensemble":>10}')
        print('-' * 42)

        best_alpha = 1.0
        best_mirex = 0.0

        for alpha_int in range(0, 105, 5):
            alpha = alpha_int / 100.0
            result = evaluate_ensemble_on_compositions(
                args.neural_predictions, args.label_dir, args.splits, alpha,
            )
            print(f'{alpha:>8.2f} {result["neural_mirex"]:>10.4f} '
                  f'{result["classical_mirex"]:>10.4f} {result["ensemble_mirex"]:>10.4f}')
            if result['ensemble_mirex'] > best_mirex:
                best_mirex = result['ensemble_mirex']
                best_alpha = alpha

        print(f'\nBest alpha={best_alpha:.2f}, Ensemble MIREX={best_mirex:.4f}')
        result = evaluate_ensemble_on_compositions(
            args.neural_predictions, args.label_dir, args.splits, best_alpha,
        )

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    output = {k: v for k, v in result.items() if k != 'per_composition'}
    output['per_composition'] = result['per_composition']
    with open(args.output, 'w') as f:
        json.dump(output, f, indent=2)
    print(f'Saved to {args.output}')


if __name__ == '__main__':
    main()
