#!/usr/bin/env python3
"""
Neural + Classical ensemble key detector.

Combines neural model softmax outputs with classical profile-based correlation
scores using a validation-tuned weighting parameter alpha:

    final_key = argmax(alpha * neural_softmax + (1 - alpha) * classical_dist)

The ensemble exploits complementary strengths: neural models capture learned
local tonal patterns while classical algorithms encode explicit music theory
knowledge from key profiles.

IMPORTANT: Requires prediction files with softmax probabilities (generated by
evaluate_harmonic_context_model.py with --save-predictions). Without softmax,
the neural side falls back to one-hot predictions which limits blending quality.

Usage:
    python ensemble_key_detector.py \
        --neural-predictions research_data/ablation_A1_predictions.json \
        --splits research_data/composition_splits.json
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Dict, List, Sequence, Tuple


def _resolve_label_path(label_dirs: Sequence[str], cid_int: int) -> str | None:
    """Search label_dirs in order for a per-composition label file.

    Returns the first matching path, or None if not found. Mirrors the
    training-time search order used in load_records_from_manifest().
    """
    filename = f'{cid_int:04d}.json'
    for d in label_dirs:
        candidate = os.path.join(d, filename)
        if os.path.isfile(candidate):
            return candidate
    return None


def _coerce_label_dirs(label_dirs, label_dir: str | None = None) -> List[str]:
    """Accept either a list, a comma-separated string, a single dir, or None."""
    if label_dirs is None or label_dirs == '':
        return [label_dir] if label_dir else []
    if isinstance(label_dirs, str):
        return [d.strip() for d in label_dirs.split(',') if d.strip()]
    return list(label_dirs)

import numpy as np

from harmonic_context_model import KEY_LABELS, key_to_index
from evaluate_harmonic_context_model import mirex_weighted_score, bootstrap_mirex_ci
from evaluate_classical_baseline import (
    build_pitch_class_histogram,
    detect_key_ensemble,
    pearson_correlation,
    PROFILES,
    ENSEMBLE_WEIGHTS,
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def classical_score_distribution(notes: List[Dict]) -> np.ndarray:
    """Compute a 24-dim classical key score distribution from notes.

    Uses the weighted ensemble of K-K, Temperley, and A-S profiles.
    Normalizes correlation scores to a probability-like distribution via softmax.

    Returns:
        24-dim array that sums to 1.0
    """
    histogram = build_pitch_class_histogram(notes)
    scores = np.zeros(24)
    # Iterate ENSEMBLE_WEIGHTS, not PROFILES — PROFILES was extended in commit
    # 2fb8271 (v0.9.2) with bellman_budge + aarden_essen but ENSEMBLE_WEIGHTS
    # remains the legacy 3-profile dict (KK + TE + AS) for backward compatibility
    # with Phase 1/2 results. Iterating PROFILES instead would KeyError on the
    # two new profiles. (Bug surfaced 2026-04-14 during Phase A Track 1.)
    for name, weight in ENSEMBLE_WEIGHTS.items():
        profile = PROFILES[name]
        for root in range(12):
            rotated = [histogram[(root + i) % 12] for i in range(12)]
            corr_major = pearson_correlation(rotated, profile['major'])
            corr_minor = pearson_correlation(rotated, profile['minor'])
            scores[root] += weight * corr_major
            scores[root + 12] += weight * corr_minor
    # Normalize to probability distribution via softmax with temperature
    # Temperature=0.1 makes the distribution peakier (classical is confident)
    scores_exp = np.exp((scores - scores.max()) / 0.1)
    return scores_exp / scores_exp.sum()


def ensemble_evaluate_composition(
    neural_preds: List[List[int]],
    neural_softmax: List[List[float]] | None,
    classical_dist: np.ndarray,
    alpha: float,
) -> List[Tuple[int, int]]:
    """Combine per-note neural predictions with global classical distribution.

    Args:
        neural_preds: List of [neural_pred, true_key] pairs
        neural_softmax: Optional list of 24-dim softmax vectors per note
        classical_dist: 24-dim classical score distribution (same for all notes)
        alpha: Weight for neural model (1.0 = neural only, 0.0 = classical only)

    Returns:
        List of (ensemble_pred, true_key) tuples
    """
    results = []
    has_softmax = neural_softmax is not None and len(neural_softmax) == len(neural_preds)

    for i, (neural_pred, true_key) in enumerate(neural_preds):
        if has_softmax:
            neural_score = np.array(neural_softmax[i])
        else:
            # Fallback: one-hot (less effective but backwards-compatible)
            neural_score = np.zeros(24)
            neural_score[neural_pred] = 1.0

        combined = alpha * neural_score + (1.0 - alpha) * classical_dist
        ensemble_pred = int(np.argmax(combined))
        results.append((ensemble_pred, true_key))

    return results


def evaluate_ensemble_on_compositions(
    neural_pred_file: str,
    label_dirs,
    splits_path: str,
    alpha: float,
    split_name: str = 'test',
) -> Dict:
    """Evaluate neural + classical ensemble on a dataset split.

    Args:
        neural_pred_file: Path to JSON with neural predictions and optional softmax.
        label_dirs: Label source(s). Accepts a list of directories, a
            comma-separated string, or a single directory path. The first
            matching file wins (training-time search order).
        splits_path: Path to composition_splits.json.
        alpha: Weight for neural model (1.0 = neural only, 0.0 = classical only).
        split_name: Which split to evaluate on ('test' or 'validation').

    Returns:
        Dict with MIREX scores, accuracy, and per-composition breakdown.
    """
    dirs = _coerce_label_dirs(label_dirs)
    if not dirs:
        raise ValueError('evaluate_ensemble_on_compositions: no label directory supplied')

    with open(neural_pred_file, 'r') as f:
        neural_data = json.load(f)

    has_softmax = neural_data.get('has_softmax', False)
    if not has_softmax:
        print('WARNING: Prediction file has no softmax. Falling back to one-hot '
              'neural predictions — ensemble quality will be limited.')

    # Phase A Track 1 fix (2026-04-14): the test composition set comes from the
    # predictions JSON itself, NOT from composition_splits.json. The audited
    # findings doc §4.2 attributed the "15.6% of test set" symptom to label-dir
    # resolution; the multi-dir fix in 7bcf9ab was necessary but not sufficient.
    # The deeper issue is that the predictions JSON is keyed on whichever split
    # the evaluator used (manifest-mode test = 41 ATEPP files; legacy split =
    # 58 compositions), and the two split sources disagree on which composition
    # IDs are "test". Filtering predictions through composition_splits.json
    # collapses the intersection to ~5 compositions. By using the predictions'
    # own composition IDs we evaluate the same set the underlying neural eval
    # already reported on. The `splits_path` arg is now informational only and
    # may be omitted; it is kept for backwards compatibility.
    pred_comp_ids = [str(c['composition_id']) for c in neural_data['compositions']]

    test_records = {}
    missing_ids: List[int] = []
    for cid_str in pred_comp_ids:
        try:
            cid_int = int(cid_str)
        except (TypeError, ValueError):
            continue
        path = _resolve_label_path(dirs, cid_int)
        if path is None:
            missing_ids.append(cid_int)
            continue
        with open(path, 'r') as f:
            test_records[cid_str] = json.load(f)
    if missing_ids:
        print(
            f'NOTE: {len(missing_ids)} of {len(pred_comp_ids)} compositions in the '
            f'predictions file have no label file across {dirs}; they are excluded.'
        )
    print(
        f'Evaluating ensemble on {len(test_records)} compositions '
        f'(from predictions JSON; splits_path={splits_path} is informational only).'
    )

    total_mirex = {'neural': 0.0, 'classical': 0.0, 'ensemble': 0.0}
    total_correct = {'neural': 0, 'classical': 0, 'ensemble': 0}
    total_count = 0
    per_comp = []

    for comp in neural_data['compositions']:
        comp_id = str(comp['composition_id'])
        preds = comp['predictions']
        softmax = comp.get('softmax', None) if has_softmax else None
        if not preds:
            continue

        # Get classical score distribution
        record = test_records.get(comp_id)
        if record is None:
            continue
        notes = record.get('notes', [])
        if not notes:
            continue

        classical_dist = classical_score_distribution(notes)
        classical_key = int(np.argmax(classical_dist))

        # Ensemble
        ensemble_preds = ensemble_evaluate_composition(
            preds, softmax, classical_dist, alpha,
        )

        comp_mirex = {'neural': 0.0, 'classical': 0.0, 'ensemble': 0.0}
        comp_correct = {'neural': 0, 'classical': 0, 'ensemble': 0}
        n = len(preds)

        for (np_, t), (ep, _) in zip(preds, ensemble_preds):
            nm = mirex_weighted_score(np_, t)
            cm = mirex_weighted_score(classical_key, t)
            em = mirex_weighted_score(ep, t)
            comp_mirex['neural'] += nm
            comp_mirex['classical'] += cm
            comp_mirex['ensemble'] += em
            total_mirex['neural'] += nm
            total_mirex['classical'] += cm
            total_mirex['ensemble'] += em
            if np_ == t: total_correct['neural'] += 1
            if classical_key == t: total_correct['classical'] += 1
            if ep == t: total_correct['ensemble'] += 1
            total_count += 1
            comp_correct['neural'] += (np_ == t)
            comp_correct['classical'] += (classical_key == t)
            comp_correct['ensemble'] += (ep == t)

        per_comp.append({
            'composition_id': comp_id,
            'mirex': comp_mirex['ensemble'] / n,
            'neural_mirex': comp_mirex['neural'] / n,
            'classical_mirex': comp_mirex['classical'] / n,
            'accuracy': comp_correct['ensemble'] / n,
            'n_predictions': n,
        })

    return {
        'alpha': alpha,
        'has_softmax': has_softmax,
        'neural_mirex': total_mirex['neural'] / max(total_count, 1),
        'classical_mirex': total_mirex['classical'] / max(total_count, 1),
        'ensemble_mirex': total_mirex['ensemble'] / max(total_count, 1),
        'neural_accuracy': total_correct['neural'] / max(total_count, 1),
        'classical_accuracy': total_correct['classical'] / max(total_count, 1),
        'ensemble_accuracy': total_correct['ensemble'] / max(total_count, 1),
        'total_predictions': total_count,
        'per_composition': per_comp,
    }


def search_alpha_on_validation(
    val_pred_file: str,
    val_label_dirs,
    splits_path: str,
) -> Tuple[float, float]:
    """Grid-search for the best ensemble alpha on the validation split.

    Searches alpha in [0.00, 0.05, ..., 1.00] and returns the value that
    maximises MIREX on the validation set.  This keeps the test set unseen
    during hyperparameter selection, preventing data leakage.

    Args:
        val_pred_file: Path to validation-split neural predictions JSON.
        val_label_dir: Directory with per-composition label files for the
            validation compositions.
        splits_path: Path to composition_splits.json (uses 'validation' key).

    Returns:
        (best_alpha, best_mirex) tuple.
    """
    print('Grid-searching alpha on VALIDATION split...')
    print(f'{"Alpha":>8} {"Neural":>10} {"Classical":>10} {"Ensemble":>10}')
    print('-' * 42)

    best_alpha = 1.0
    best_mirex = 0.0

    for alpha_int in range(0, 105, 5):
        alpha = alpha_int / 100.0
        result = evaluate_ensemble_on_compositions(
            val_pred_file, val_label_dirs, splits_path, alpha,
            split_name='validation',
        )
        print(f'{alpha:>8.2f} {result["neural_mirex"]:>10.4f} '
              f'{result["classical_mirex"]:>10.4f} {result["ensemble_mirex"]:>10.4f}')
        if result['ensemble_mirex'] > best_mirex:
            best_mirex = result['ensemble_mirex']
            best_alpha = alpha

    print(f'\nBest alpha on validation: {best_alpha:.2f}  '
          f'(val MIREX={best_mirex:.4f})')
    return best_alpha, best_mirex


def main() -> None:
    parser = argparse.ArgumentParser(description='Neural + Classical ensemble key detector')
    parser.add_argument('--neural-predictions', required=True,
                        help='Path to neural model predictions JSON (with softmax) for the TEST set')
    parser.add_argument('--val-predictions', default=None,
                        help='Path to neural model predictions JSON for the VALIDATION set. '
                             'When provided, alpha is tuned on validation and evaluated once '
                             'on test, preventing data leakage.')
    parser.add_argument('--splits', default=os.path.join(BASE_DIR, 'research_data', 'composition_splits.json'))
    parser.add_argument(
        '--label-dir',
        default=os.path.join(BASE_DIR, 'research_data', 'score_key_labels'),
        help='Single label directory (backwards-compatible). Use --label-dirs for multi-corpus eval.',
    )
    parser.add_argument(
        '--label-dirs', default=None,
        help='Comma-separated list of label directories, searched in order '
             '(training-time search order). When set, overrides --label-dir.',
    )
    parser.add_argument('--val-label-dir', default=None,
                        help='Single label directory for validation compositions. '
                             'Defaults to --label-dir / --label-dirs if not specified.')
    parser.add_argument('--val-label-dirs', default=None,
                        help='Comma-separated list of validation label directories. '
                             'When set, overrides --val-label-dir.')
    parser.add_argument('--alpha', type=float, default=None,
                        help='Neural weight (0-1). If not set, grid-searches for best alpha.')
    parser.add_argument('--output', default=os.path.join(BASE_DIR, 'research_data', 'ensemble_eval.json'))
    args = parser.parse_args()

    # Resolve test label dirs. Prefer --label-dirs plural if provided.
    test_label_dirs = _coerce_label_dirs(args.label_dirs, args.label_dir)
    # Resolve val label dirs. Fall back to test dirs if nothing specified.
    if args.val_label_dirs:
        val_label_dirs = _coerce_label_dirs(args.val_label_dirs, None)
    elif args.val_label_dir:
        val_label_dirs = _coerce_label_dirs(None, args.val_label_dir)
    else:
        val_label_dirs = test_label_dirs

    print(f'Test label dirs:       {test_label_dirs}')
    print(f'Validation label dirs: {val_label_dirs}')

    if args.alpha is not None:
        # ---- Fixed alpha: evaluate directly on test ----
        result = evaluate_ensemble_on_compositions(
            args.neural_predictions, test_label_dirs, args.splits, args.alpha,
        )
        print(f'Alpha={args.alpha:.2f}:')
        print(f'  Neural MIREX:    {result["neural_mirex"]:.4f}')
        print(f'  Classical MIREX: {result["classical_mirex"]:.4f}')
        print(f'  Ensemble MIREX:  {result["ensemble_mirex"]:.4f}')

    elif args.val_predictions is not None:
        # ---- Proper workflow: tune on validation, evaluate once on test ----
        best_alpha, val_mirex = search_alpha_on_validation(
            args.val_predictions, val_label_dirs, args.splits,
        )

        print(f'\nEvaluating on TEST set with alpha={best_alpha:.2f} ...')
        result = evaluate_ensemble_on_compositions(
            args.neural_predictions, test_label_dirs, args.splits, best_alpha,
        )
        print(f'  Neural MIREX:    {result["neural_mirex"]:.4f}')
        print(f'  Classical MIREX: {result["classical_mirex"]:.4f}')
        print(f'  Ensemble MIREX:  {result["ensemble_mirex"]:.4f}  '
              f'(alpha={best_alpha:.2f}, tuned on validation)')

    else:
        # ---- Legacy fallback: grid-search on test (data leakage) ----
        print('WARNING: --val-predictions not provided. Grid-searching alpha on '
              'the TEST set — this is data leakage and should only be used for '
              'exploratory analysis, NOT for reporting final results.')
        print(f'{"Alpha":>8} {"Neural":>10} {"Classical":>10} {"Ensemble":>10}')
        print('-' * 42)

        best_alpha = 1.0
        best_mirex = 0.0

        for alpha_int in range(0, 105, 5):
            alpha = alpha_int / 100.0
            result = evaluate_ensemble_on_compositions(
                args.neural_predictions, test_label_dirs, args.splits, alpha,
            )
            print(f'{alpha:>8.2f} {result["neural_mirex"]:>10.4f} '
                  f'{result["classical_mirex"]:>10.4f} {result["ensemble_mirex"]:>10.4f}')
            if result['ensemble_mirex'] > best_mirex:
                best_mirex = result['ensemble_mirex']
                best_alpha = alpha

        print(f'\nBest alpha={best_alpha:.2f}, Ensemble MIREX={best_mirex:.4f}')
        result = evaluate_ensemble_on_compositions(
            args.neural_predictions, test_label_dirs, args.splits, best_alpha,
        )

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    output = {k: v for k, v in result.items() if k != 'per_composition'}
    output['per_composition'] = result['per_composition']
    with open(args.output, 'w') as f:
        json.dump(output, f, indent=2)
    print(f'Saved to {args.output}')


if __name__ == '__main__':
    main()
